spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///fms?serverTimezone=UTC
    password: 122425
    username: root
servlet:
  multipart:
    max-file-size: 5MB
server:
  port: 8888
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fms.pojo
